---
title: 'Report: WaSH data preparation'
author: "Steve and Jonathan"
date: ' `r as.Date(Sys.time())` '
output:
  word_document: default
  html_document:
    fig_caption: yes
---


```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE
	, warning = FALSE
	, message = FALSE
	, fig.width = 10
	, fig.height = 10
	, fig.align="center"
	, results = "asis")
options(width = 12)

library(ggplot2)
theme_set(theme_bw() +
	theme(panel.spacing=grid::unit(0,"lines")))

library(forcats)
library(ggpubr)

library(dplyr)
library(DT)
library(scales)
library(dotwhisker)
library(ggstance)
library(corrplot)
library(lme4)
library(splines)

load("analysis_variables.rda")
load("overall_missing_tables.rda")
source("funs/ggplot_theme.R"); ggtheme()
load("washdataInspect_plots.rda")
```

<!-- ## Concerns with APHRC approach -->

<!-- **Construction of indices** -->

<!-- - Source of drinking water, type of toilet and toilet facilities, which are the response, were used in the construction of indices e.g., wealth index. [See](../docs/aphrc_wealth_index_construct_Rutstein.pdf). -->

<!-- ## Our choices -->

### Response variables

- Response variables were categorized as `Improved` or `Unproved` based on the following criteria


|                                     	| Improved                                                                                                                                                                                   	| Unimproved                                                                                                                                                                                                                                                                                  	|
|-------------------------------------	|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| <br>Drinking water source           	| <br>Piped water into dwelling, plot or yard<br>Public tap/standpipe<br>Tube well / borehole<br>Protected dug well with hand pump<br>Protected spring<br>Rainwater collection from the roof 	| Unprotected dug well<br>Unprotected spring<br>Small water vendor (cart with small tank or drum)<br>Bottled water<br>Tanker truck<br>Rainwater collection from surface run off. Surface water (river, dam, lake, pond, stream, canal, irrigation channels)<br>Protected dug well with bucket 	|
| Toilet facility type                	| Flush / pour flush to piped sewer system or septic tank or pit latrine<br>VIP latrine<br>Pit latrine with slab<br>Composting toilet                                                        	| Flush / pour flush to elsewhere e.g. to open drain<br>Pit latrine without slab (slab with holes) /open pit<br>Bucket<br>Hanging toilet / hanging latrine<br>No facilities or bush or field                                                                                                  	|
| <br>Garbage disposal method<br><br> 	| Garbage dump<br>Private pits<br>Public pits<br>Proper garbage disposal services<br>Other organized groups such as the national youth service                                               	| In the river<br>On the road, railway line/station<br>In drainage/sewage/trench<br>Vacant/abandoned house/plot/field<br>No designated place/all over<br>Street boys/urchins<br>Burning<br>Other                                                                                              	|

****

\vspace*{2xm}

See summary tables in `compareCalculations.xlsx` in the Makefile


### Predictors

**Demographics**

- `age`
- `gender`

- `slumarea`

	Slum area (Korogocho and Viwandani)

- `hhsize` 

	Number of household members (in this + other structure)

- `intvwyear`

	The interview year. The baseline survey that defined the initial population for the NUHDSS was carried in `2002`. Subsequent interviews were conducted until 2015. As such, we exclude `2002` interviews in our analysis.

**Dwelling index**
	
- The following household amenities questions are used to compute dwelling index

	- **Main material of the floor**, broadly recoded into:
		- Finished (cement/concrete (tiles/slab), vinyl (PVC)/asphalt strips, polished wood/tiles/carpet, asbestos sheet) - **4**
		- Natural (earth/mud/dung/sand) - **3**
		- Rudimentary (wood planks, carton/plastic sheets, gunny bags, woven mat (sisal/nylon)) - **2**
	
	- **Main material of the roof**, recoded into:
		- Finished (tiles, asbestos sheet, cement/concrete/stone) - **4**
		- Natural (cement/concrete/stone) - **3**
		- Rudimentary (iron sheets (corrugated), metal sheets/tin, wood/timber, plastic sheets, cardboard sheets) - **2**
		- Others - **1**

	- **Main material of the wall**, recoded into:
		- Finished (stone/quarry stones, concrete blocks/slab, wood/timber, burnt bricks, asbestos sheet) - **4**
		- Natural (dirt/mud/dung) - **2**
		- Rudimentary (iron sheets/mabati, cemented mud, tin/metal sheets, cardboard sheets, carton/plastic, unspecified, plywood/chipboard) - **2**
		- Others - **1**

	- **Main source of cooking fuel**, recoded into:
		- electricity (KPLC, electricity:other source) - **7**
		- gas - **6**
		- kerosene/paraffin - **5**
		- charcoal (charcoal, briquettes/mud charcoal) - **4**
		- firewood - **3**
		- animal/crop residue (animal waste, crop residue/saw dust) - **2**
		- others (plastics/gunny bags/cartons/papers, other) - **1**

	- **Main source of lightling**
		- electricity (KPLC, electricity:other source) - **7**
		- gas - **6**
		- kerosene/paraffin - **5**
		- candles - **4**
		- charcoal - **3**
		- firewood - **2**
		- others (flashlight/phone/rechargable/solar lamps, plastics/gunny bags/cartons/papers, doesn't light the house at all, other) - **1**

	- **Place of dwelling ownership**
		- Owned (inherited, constructed, purchased) - **4**
		- Rental (from individual, from government, from parastatal, from private company, from local authority) - **3**
		- Free - **2**
		- Others (belongs to/rent paid by relative/friend, belongs to/rent paid by employer, caretaker/security, belongs to/rent paid by religious entity) - **1**

- Dwelling index is derived from the first principal component score of logistic PCA based on dummy indicator variables generated from these variables.

	<!-- - **PCA**: [Click here to open](./dwelling_pca_plot.Rout.pdf) -->
	<!-- - **MCA**: [Click here to open](./dwelling_mca_plot.Rout.pdf) -->

**Assets ownership index**

- Assets information on whether the household owned any (yes/no), either the household or elsewhere, of the following household assets

	|	<!-- -->			|	<!-- -->						|			<!---->					|<!----> 					|
	|--------------	|------------------------	|--------------------------	|---------------------	|
	| Vehicle      	| Sewing machine         	| Torch                    	|Livestock or poultry	|
	| Motorcycle   	| Electric iron          	| Kerosene lamp with glass 	|Grow crops					|
	| Bicycle      	| Fan                    	| Kerosene stove           	|								|
	| Refrigerator 	| Telephone/mobile phone 	| wall clock               	|								|
	| Television   	| Electric/gas stove     	| Mattress                 	|								|
	| Radio/stereo 	| Sofa set               	| Blankets                 	|								|
	| DVD/VCD/VCR  	| Table                  	| Bed                      	|								|
	----------------------------------------------------------------------

- Logistic PCA is performed and first PC scores are used as a proxy for assets ownership index.
	<!-- - **Logistic PCA**: [Click here to open](./ownership_pca_plot.Rout.pdf) -->


**Household income**

- Estimated total income for the household in the last 30 days. 
	- < KES 1,000 - **1**
	- KES 1,000-2,499 - **2**
	- KES 2,500-4,999 - **3**
	- KES 5,000-7,499 - **4**
	- KES 7,500-9,999 - **5**
	- KES 10,000-14,999 - **6**
	- KES 15,000-19,999 - **7**
	- KES 20,000+ - **8**

- Simply ranked

**Total expenditure**

- Amount (KES) spent on the following, in the last 7 days, constitutes household expenditure:
	- Food
	- Energy
	- Water
	- Rent
- Sum constitutes total expenditure

**Household food consumption**

- How do you describe the food eaten by your household in the last 30 days?
	- Had enough (not always foods wanted, foods wanted)
	- Didn't have enough (didn't have enough:sometimes, didn't have enough:often)


**Shocks index (Simply counted)**

- Whether the household experienced any of the following shocks/problems in the last year (yes/no)?
	
	|	<!-- -->			|	<!-- -->						|			<!---->					|
	|--------------	|------------------------	|--------------------------	|
	| Fire	      	| Eviction		         	| Rape	                    	|
	| Floods		   	| Demolition	          	| Stabbing						 	|
	| Mugging      	| Severe illness          	| Lay-off			           	|
	| Theft			 	| Death						 	|				               	|
	----------------------------------------------------------------------
	

**Household self rating**

- On a scale of 1 (poorest) - 10 (richest), how does the household compare to others in the community.


<!-- ## Missing data -->

<!-- - APHRC categorized missing data as follows ([See](./docs/ddi-documentation-english-54.pdf)): -->
<!-- 	- `missing:impute`: Missing information and can be imputed -->
<!-- 	- `refused`: Assigned to any variable where the respondent refused to answer or participate -->
<!-- 	- `Don't know`: Assigned to any variables where the respondent did not know the answer -->
<!-- 	- `NIU (not in universe)`: Assigned to any variable where the unit (in this case, household) is not in the universe/are not eligible to answer the question -->

<!-- - To handle missing data: -->
<!-- 	- Any entry falling in any of the missing data category outlined above is recoded as `NA`  -->
<!-- 	- All variables with at least $30\%$ missing values are excluded and then any case with missing values in any of the remaining variables are excluded -->


<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- ```{r} -->
<!-- datatable(miss_category_summary_df, rownames = FALSE) -->
<!-- ``` -->

<!-- - Missing proportion for all the missing categories except `missing:impute`. -->

<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- ```{r} -->
<!-- datatable(miss_df, rownames = FALSE) -->
<!-- ``` -->

<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- - The table below shows the percentage of missingness per case. Complete cases used for analysis are `r miss_percase_df$Freq[miss_percase_df$Var1==0]`, representing `r percent(miss_percase_df$Freq[miss_percase_df$Var1==0]/sum(miss_percase_df$Freq))` of all the cases. -->

<!-- ```{r} -->
<!-- colnames(miss_percase_df) <- c("Percent miss per case", "Number of cases") -->
<!-- datatable(miss_percase_df, rownames = FALSE) -->
<!-- ``` -->

<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- - For the selected variables, most missing cases are in the years $2002 - 2005$, consequently, exclusion criteria above excludes these years.  -->

<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- ```{r} -->
<!-- tab_freq <- (as.data.frame(miss_peryear_df) -->
<!-- 	%>% tidyr::spread(Var2, Freq) -->
<!-- 	%>% data.table::setnames("Var1", "Percent Miss") -->
<!-- ) -->
<!-- datatable(tab_freq, options = list(pageLength = 20), rownames = FALSE) -->
<!-- ``` -->

<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- ## Multiple interviews per household per year -->

<!-- - According to APHRC, there should be only 1 interview per household per year. However, we found a few cases which had multiple interviews. See the table below -->


<!-- ```{r} -->
<!-- tab_freq <- (as.data.frame(tab_intperyear) -->
<!-- 	%>% data.table::setnames(c("Var1", "Freq"), c("Interviews per HH per year", "Total")) -->
<!-- ) -->
<!-- datatable(tab_freq, options = list(pageLength = 20), rownames = FALSE) -->
<!-- ``` -->

<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- - In households where there are more than 1 interviews, we select the last interview based on interview date. -->


<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- ## Incorporating service status in the previous year -->

<!-- - There are two ways we can incorporate service status in the service previous year: -->
<!-- 	- Have two separate models: model with first observation data only; and model excluding the first year data -->
<!-- 	- Or, a single model but categorize the service status in the previous year -->

<!-- **Two separate models** -->

<!-- - To understand what data we're losing in our gain-loss model, and think about whether we should consider imputing data for missing years, we want to know for each household how many surveys have data which can't be used in the gain-loss model because the previous year is missing. -->
<!-- - The first observation for any household is used in the baseline model (and never has a previous year), so we don't count these as missing. -->
<!-- - For example, in the Table below, household 1 has 2 consecutive interviews, so `nprev_miss2` (truly missing previous interviews) is 0.  Household 818 has 5 interviews in total, but there is are gas between years 3 \& 5, 5 \& 7 and 7 \& 9, so `nprev_miss2` is 3.  -->

<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- ```{R} -->
<!-- datatable(prevcases_df_summary, rownames = FALSE, options = list(pageLength = 8)) -->
<!-- ``` -->


<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- - Figure below shows the distribution of all interviews missing at least 1 interview in the previous year (first year interviews included), representing `r percent_miss_consec` of all the cases.  -->


<!-- ```{R fig.width = 5, fig.height = 5} -->
<!-- print(consec_all_plot) -->
<!-- ``` -->

<!-- \vspace*{2cm} -->
<!-- **** -->

<!-- - Ignoring the first year interviews (`r percent_year0` which can be modeled separately), the proportion of interviews we are actually dropping due to missing preceding year interviews are `r  percent_miss_consec_noyr0 `(about `r  percent_miss_consec_noyr0_all` of all the interviews). -->

<!-- ```{R, fig.width = 5, fig.height = 5} -->
<!-- print(consec_noyr0_plot) -->
<!-- ``` -->

<!-- \vspace*{2cm} -->
<!-- **** -->


<!-- **A single model** -->

<!-- - To handle missing data problems in our gain-loss model, and to avoid fitting a separate base year model, service status in the previous year are categorized as follows: -->
<!-- 	- **Base year**: First household specific observational year -->
<!-- 	- **Not observed**: Immediate preceding year not observed -->
<!-- 	- **Unimproved**: Observed but unimproved service -->
<!-- 	- **Improved**: Observed improved service -->

<!-- - and then a single model fitted. We use this approach. -->

<!-- ## Distribution of services -->

<!-- - The Figure below shows the proportion of households with improved services over years. The dotted lines represent the household average for each service over the entire study period. -->


<!-- ```{R distributions1, fig.width = 7, fig.height = 8} -->
<!-- print(prop_plot) -->
<!-- ``` -->

<!-- ### No. of interviews completed by HH -->

<!-- - If every household was interviewed per year, we would expect $10$ interviews per household. On the contrary, over $40\%$ of the households only had $1$ interview over the entire study period. -->
<!-- - Denominator is number of HH (expected number of interviews per year) -->

<!-- ```{R fig.width = 5, fig.height = 5} -->
<!-- print(n_interviews_plot) -->
<!-- ``` -->

<!-- ### No. of interviews per year -->

<!-- - The Figure below shows the percentage of interviews per year. -->
<!-- 	- We may need to seek for clarification on low percentage in $2003$  -->

<!-- ```{R fig.width = 5, fig.height = 5} -->
<!-- print(year_plot) -->
<!-- ``` -->

<!-- ## Current vs previous year service status (JD: Status Quo?) -->

<!-- - We track service transitions from the previous year to the current year (within households): -->
<!-- 	- **All -**: Service not improved both in the previous and in the current year -->
<!-- 	- **All +**: Improved service both in the previous and current year -->
<!-- 	- **No prev.**: Had no service in the previous year (missing interview in the previous year) -->
<!-- 	- **Gain**: Unimproved service in the previous year but improved service in the current year -->
<!-- 	- **Loss**: Improved service in the previous year but unimproved service in the current year -->

<!-- ```{R fig.width = 5, fig.height = 5} -->
<!-- print(status_quo_plot) -->
<!-- ``` -->

<!-- ## Modelling  -->

<!-- - A single model fitted with service status in the previous year categorized as described above. -->
<!-- - A total of `r nint_all` were done between $2006 - 2015$. -->
<!-- - There are `r nhhid` households, interviewed in at least one of the interview years. -->

<!-- ### Variables -->

<!-- - As described above with additional random effect term -->
<!-- 	- `(services-1|hhid)` -->
<!-- - Fitted in `glmmTMB`. `lme4` is too slow. -->


<!-- ## Results -->

<!-- ### Effect sizes -->

<!-- <a href="./git_push/washEffectsize_plots.Rout.pdf" target="_blank">Click here to open</a> -->


<!-- ### Predictions -->

<!-- - Plots are on the scale of the logit scale, but the vertical axis is labelled on the response scale. This preserves the (linear) structure of the model while permitting interpretation on the probability scale. **(Steve -> JD: Converting everything to response scale make the CI too narrow)** -->

<!-- **Logit scale** -->

<!-- [Click here to open](./washPredEffects_plots.Rout.pdf) -->


<!-- **Response scale** -->

<!-- [Click here to open](./washPredEffects_Resp_plots.Rout.pdf) -->
